#+title: Physical Computing1 Org File
#+author: Ashley Sagar

[[https://learn.gold.ac.uk/course/view.php?id=27909][Physcom1 VLE]]

[[https://www.doc.gold.ac.uk/Hatchlabs/][Hatchlabs www]]


[[https://itp.nyu.edu/physcomp/lessons/][NYU PHYSCOM]]
[[https://itp.nyu.edu/physcomp/videos/][NYU videos]]



* Week_01

** Module overview

 - idea, prototype, iterate


 - Electricity
   - voltage - preassure
   - current - amount of energy pushed thru a circuit
   - resistance - ohms- how much energy has been squeezed out of the circuit

     - Power - Watts:
       - Voltage x current
       - Power(P) = Current(I) * Voltage(V)
       - 


  - Breadboarding
    1. simple circuit from powered-board(fakeduino)
    2. Soldered up an LED with a 220ohm resistor attached to tthe positive leg.
    
	



  some text here



* Week_02

** multimeter
- testing continuity
- ohms
- v~ = AC power
- v w 2 lines = DC current
  - checked with a 9V battery
- Used desktop psu to check current
- code
  - variables
  - functions
  - conditionals
- Blinking light sketch
  -changed blonking light sketch
- added a 2nd led and changed the timings


- Debugging


- Schematics
- [[https://www.circuit-diagram.org/editor/][schematic maker]]
- [[https://easyeda.com/][EASY EDA]]
- [[https://robhallart.github.io/PhysCompIdeaDice/][idea generator]]
- [[https://itp.nyu.edu/physcomp/videos/videos-schematic-diagrams/][nyu pyscom schematic vids]]

  
** HOMEWORK
 • Please make the most interesting button you can.
• You can ONLY USE BUTTONS as your input but you can USE LEDs or the Serial Monitor as your output.
• Think about the meaning of what you make, how it will be used, the colours you choose, the design of your device.
• Can you make it tell a story? Can you make it surprise the user?
• Deliverables:
• Upload this assignment to the VLE and include: A short video of the project (1 minute or less) , your code, a
schematic of your circuit. (This can be hand drawn or done on a computer)
• Post just the video of your device to the class forum so we can all see everyone's work.
• Please think of this brief as an opportunity to try things out, the result does not have to be perfect, feel free to
try things and fail, to play, to experiment, to get things wrong.
  

* Week_03

 - recap
   - schematics
   - code
     - statments
     - functions
     - variables
     - conditionals


 - repetition
   - forloops
     for(int i; i < 100; i++){
     println(i); // prints 0 - 99
     }
   - incriment
     1. i = i + 1;
     2. i++;
     3. i += 1;
     4. i + otherValue


 - analog vs digital
   - digital is either on or off
   - less susceptable to inteference


 - analoG
   - can be any value and move smoothly among values
   - prone to inteference


 - PWM -pulse width modulation
   - emulatiung an analog signal
   - use it to dim an led
   -

     - The Arduino Mega has 15 PWM Pins on :
   - 2 - 13, 44 - 46

 - analogWrite


- LDR Light dependent resistor
  - must use a 10k resitor


- RGB LED
  - 3 leds in 1
  - 3 resistors


- Servo Motors
  - 3 WIRES
  - yellow - data
  - red
  - black


** HOMEWORK

*** EXPECT THE UNEXPECTED

You should make a physical installation that subverts my expectations.
The goal of this mini-project is to build a physical installation (for example this could be an art work, game, some thing
useful, a product, an interactive installation etc) that has at least one input and one output and does something
unexpected. Think about what the user/viewer will: SEE, HEAR, FEEL. Think about how to prototype your installation
and test it, how will people know what to do, what feedback will they get, will there be interaction. Think about what
you would expect your installation to do and then make it do the opposite.
Please include, at the minimum, the following: - one input (sensor) - one output (actuator)
Upload this assignment to the VLE and include: A short video of the project (1 minute or less) , your code, a schematic
of your circuit. The schematic can be hand drawn or created using other software you choose - for example Fritzing
or EasyEDA. ALSO Post the short video of your device to the class forum so we can all see everyone's work. Please
upload everything to the VLE and forum.
Please think of this brief as an opportunity to try things out, the result does not have to be perfect, feel free to try
things and fail, to play, to experiment, to get things wrong.

    
* Week_04

* Week_05

* Week_06

* Week_07

* Week_08

* Week_09

* Week_10
