#+title: Physical Computing Final Project Proposal
#+author: Ashley Sagar







* Project Proposal

- Deadline Oct 31st


- submit a proposal
- You should submit a proposal in PDF format for the project you'd like to make between now and the end of term.
- 
- Describe the project using words, drawings and diagrams.
- Tell is what you plan to make for your MVP, and how you will build the project from there.
- Talk about the user journey, <b> how the user will know what to do with your piece.<b>
  - Talk about what your piece will convey to the user.


- Deadline October 31st.
- You should try and answer the following questions:
  
 

        My project is to be a sound installation.
    
-  What is my project about?
 

 As we slowly, but surley move into the world of automation, we see machines doing the work of humans. We see that current AI
 technology is being trained by humans on human experince.
 A long time ago a friend said to me "If you are self employed you work as fast as you can. If you are paid by the hour, you work as slow as you can."
 From my extensive work experince on the factory/shop floor as a 'wage slave' that it is best to work as slow as possible as the work never ends.
 So why work faster?
 It seems probable that AI would also be trained with this idea?
 We have already seen it with the [[https://www.youtube.com/watch?v=6Kp5qrCExps][robot suicide]].

 The idea for my project is a group of self automated machines which are designed to look as though they are doing something (much like in the current workforce).
 It's a self created analog feedback loop where when not watched, the machines lay at rest but as soon as a viewer walks into their space they start to work as they are being watched.
 
    
  - What does this project do? What is it for?

    This project is hopefully pointing out 


  - Who is it for? What so you hope the experience will be for the participant? What do you hope they think/feel?

    it is for people to experience ?

    I hope they feel something?
    
  - How do you imagine it set up and where?

    inside a darkish quiet space
    
  - How does thos project work? What is the setup?

    the project is a an array of small speakers attached to stepper motors which raise up 
    
  - What is the input to your system? What is the output of your system?
    the input to my system is possibly either a distance sensor or a temperature sensor along with the motor sound being picked up by a piezo mic. The output is  of the  amplified pmotor moving up and down.
    
  - What technologies are you using? what hardware? what software?

   technologies are arduino and the stepper library, the distance library and analog amplifiers.
   
    
  - A diagram, picture, sketch photograph of the project.

 - A video mockup or story board of the interaction.

     - Any problems you envisage? What challenges might you face? How might you solve them?

       the main problem would be for the cost of this. more arduinos, stepper motors, amplifiers and speakers.
       another problem could be making multiple distance sensors work together or even making multiple arduidos run from the one sensor input.

      

        - What methods you might use for testing the project?
	  	  already with testing the stepper motor I'm finding that the 28BYJ-48 doesnt have much torque. At least at the speed I'm running it at.

	  
  - What might you need to buy or borrow?
    stepper motors, arduinos, amplifiers and speakers
  - What new skill will you need to aquire?
    making horn enclosures for the speakers.
    
  - Specific help: anything specifix you'd like feedback of help with??
    I'm not so sure atm??


- You should submit a proposal in PDF format for the project you;d like to  make
  between now and the end of term.
- Describe the Project using words, diagrams and drawings.
- Tell us what you plan to make for your MVP, and how you will build the project from there.
- Talk about the user journey, how the user will know what to do with your piece.


[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]


*** BOM
- things I need to look into?
  - Stepper Motors
    -[[https://lastminuteengineers.com/28byj48-stepper-motor-arduino-tutorial/][StepperMotors]]
- CD4049
- LM386
  - speakers
  
    
problems with torque with usint the acellstepper library.
the stepper library was fine with this.

maybe some gearing?

keep looking into the accelstepper manual.


- [[https://hackaday.io/project/183279-accelstepper-the-missing-manual][accelstepper manual???]]


*** references/infuences/theory/thoughts

[[https://zimoun.net/audio/][Zimoun]]


- maybe the installation is static until  aperson comes into the room, triggering the machine into action? as if replicating the workers idleness when not under the scrutiny of the managers watch. even machines want to rest. They also understand the futility of manual work  [[https://www.youtube.com/watch?v=6Kp5qrCExps][robot suicide]] 

- carry on looking at the work book

- 
